
// ── Complete manufacturer list (150+ brands) ──────────────────────────────
export const MANUFACTURERS = [
  // American
  'AC','AMC','Buick','Cadillac','Chevrolet','Chrysler','Cord','De Tomaso',
  'Dodge','Eagle','Ford','GMC','General Motors','Hudson','Hummer',
  'Lincoln','Mercury','Nash','Oldsmobile','Packard','Plymouth',
  'Pontiac','Ram','Shelby','Studebaker','Tesla','Rivian','Lucid',
  // European
  'Alfa Romeo','Aston Martin','Audi','Bentley','BMW','Bugatti',
  'Citroen','Dacia','Ferrari','Fiat','Jaguar','Koenigsegg',
  'Lamborghini','Lancia','Land Rover','Lotus','Maserati','McLaren',
  'Mercedes-Benz','MINI','Pagani','Peugeot','Porsche','Renault',
  'Rolls Royce','Saab','SEAT','Skoda','Smart','Vauxhall','Volkswagen','Volvo',
  // Japanese
  'Acura','Daihatsu','Datsun','Honda','Infiniti','Isuzu','Lexus','Mazda',
  'Mitsubishi','Nissan','Subaru','Suzuki','Toyota',
  // Korean
  'Genesis','Hyundai','Kia','SsangYong',
  // Chinese/Other
  'BYD','Geely','Great Wall','Haval','NIO','Polestar','Xpeng',
  // Classic/Special
  'Auburn','Delorean','Duesenberg','Edsel','Kaiser','Pierce-Arrow',
  'SSC','Vector','Willys',
  // Hot Wheels Originals (fantasy)
  'Hot Wheels Original','Mattel','Custom/Fantasy',
  // Trucks/Commercial
  'Freightliner','Kenworth','Mack','Peterbilt','International',
  'Unknown',
].sort();

// ── Map car name keywords → manufacturer ─────────────────────────────────
const NAME_TO_MFG: Record<string, string> = {
  // ── School Bus / HW Originals ─────────────────────────────────────────
  'surfin school bus': 'Hot Wheels Original',
  'school bus': 'Hot Wheels Original',
  'surfin school': 'Hot Wheels Original',
  'surfin': 'Hot Wheels Original',
  'bone shaker': 'Hot Wheels Original',
  'twin mill': 'Hot Wheels Original',
  'deora': 'Hot Wheels Original',
  'rip rod': 'Hot Wheels Original',
  'rodger dodger': 'Hot Wheels Original',
  'el segundo': 'Hot Wheels Original',
  'bread box': 'Hot Wheels Original',
  'fast fish': 'Hot Wheels Original',
  'ratbomb': 'Hot Wheels Original',
  'custom otto': 'Hot Wheels Original',
  'mod speeder': 'Hot Wheels Original',
  'punk rod': 'Hot Wheels Original',
  'lolux': 'Hot Wheels Original',
  // ── Datsun ───────────────────────────────────────────────────────────
  'datsun': 'Datsun',
  '240z': 'Datsun',
  '260z': 'Datsun',
  '280z': 'Datsun',
  'datsun 510': 'Datsun',
  'bluebird': 'Datsun',
  'fairlady': 'Datsun',
  // ── Barbie / Mattel ───────────────────────────────────────────────────
  'barbie': 'Mattel',
  // ── Batman / DC ───────────────────────────────────────────────────────
  'batmobile': 'DC Comics',
  'kitt': 'DC Comics',
  // ── Pontiac ───────────────────────────────────────────────────────────
  'pontiac': 'Pontiac',
  'firebird': 'Pontiac',
  'trans am': 'Pontiac',
  'gto': 'Pontiac',
  // ── AMC ───────────────────────────────────────────────────────────────
  'amc': 'AMC',
  'javelin': 'AMC',
  'amx': 'AMC',
  'gremlin': 'AMC',

  // Ford
  'mustang': 'Ford', 'f-150': 'Ford', 'f150': 'Ford', 'bronco': 'Ford',
  'gt40': 'Ford', 'gt 40': 'Ford', 'ford': 'Ford', 'maverick': 'Ford',
  'ranger': 'Ford', 'explorer': 'Ford', 'expedition': 'Ford', 'edge': 'Ford',
  'escape': 'Ford', 'focus': 'Ford', 'fusion': 'Ford', 'taurus': 'Ford',
  // Chevrolet / GM
  'camaro': 'Chevrolet', 'camaro ss': 'Chevrolet', 'copo camaro': 'Chevrolet', 'corvette': 'Chevrolet', 'silverado': 'Chevrolet',
  'chevy': 'Chevrolet', 'chevrolet': 'Chevrolet', 'chevelle': 'Chevrolet',
  'el camino': 'Chevrolet', 'blazer': 'Chevrolet', 'tahoe': 'Chevrolet',
  'suburban': 'Chevrolet', 'impala': 'Chevrolet', 'nova': 'Chevrolet',
  'monte carlo': 'Chevrolet', 'bel air': 'Chevrolet', '55 chevy': 'Chevrolet',
  '57 chevy': 'Chevrolet', 'c10': 'Chevrolet', 'ssr': 'Chevrolet',
  'cadillac': 'Cadillac', 'escalade': 'Cadillac', 'ctsv': 'Cadillac',
  'buick': 'Buick', 'gmc': 'GMC', 'sierra': 'GMC', 'canyon': 'GMC',
  // Dodge / Chrysler / Plymouth
  'dodge': 'Dodge', 'challenger': 'Dodge', 'charger': 'Dodge',
  'viper': 'Dodge', 'dart': 'Dodge', 'ram': 'Ram',
  'chrysler': 'Chrysler', 'plymouth': 'Plymouth', 'barracuda': 'Plymouth',
  'road runner': 'Plymouth', 'superbird': 'Plymouth',
  // Ferrari
  'ferrari': 'Ferrari', '458': 'Ferrari', '488': 'Ferrari', 'f40': 'Ferrari',
  'f50': 'Ferrari', 'laferrari': 'Ferrari', 'testarossa': 'Ferrari',
  '308': 'Ferrari', '599': 'Ferrari', 'enzo': 'Ferrari',
  // Lamborghini
  'lamborghini': 'Lamborghini', 'countach': 'Lamborghini',
  'huracan': 'Lamborghini', 'aventador': 'Lamborghini',
  'urus': 'Lamborghini', 'gallardo': 'Lamborghini', 'murcielago': 'Lamborghini',
  // Porsche
  'porsche': 'Porsche', '911': 'Porsche', '918': 'Porsche',
  'cayenne': 'Porsche', 'cayman': 'Porsche', 'panamera': 'Porsche',
  'boxster': 'Porsche', '356': 'Porsche', 'macan': 'Porsche',
  // BMW
  'bmw': 'BMW', 'bimmer': 'BMW', 'm3': 'BMW', 'm4': 'BMW', 'm5': 'BMW',
  'i8': 'BMW', '2002': 'BMW', '1m': 'BMW',
  // Mercedes
  'mercedes': 'Mercedes-Benz', 'benz': 'Mercedes-Benz', 'amg': 'Mercedes-Benz',
  'sls': 'Mercedes-Benz', 'g-class': 'Mercedes-Benz', 'g wagon': 'Mercedes-Benz',
  'g-wagon': 'Mercedes-Benz', 'sprinter': 'Mercedes-Benz',
  // Audi
  'audi': 'Audi', 'r8': 'Audi', 'rs6': 'Audi', 'quattro': 'Audi',
  // McLaren
  'mclaren': 'McLaren', 'p1': 'McLaren', 'senna': 'McLaren', '720s': 'McLaren',
  'elva': 'McLaren', '570': 'McLaren', 'f1': 'McLaren',
  // Bugatti
  'bugatti': 'Bugatti', 'veyron': 'Bugatti', 'chiron': 'Bugatti', 'divo': 'Bugatti',
  // Koenigsegg
  'koenigsegg': 'Koenigsegg', 'agera': 'Koenigsegg', 'jesko': 'Koenigsegg',
  'regera': 'Koenigsegg',
  // Pagani
  'pagani': 'Pagani', 'huayra': 'Pagani', 'zonda': 'Pagani',
  // Aston Martin
  'aston martin': 'Aston Martin', 'db5': 'Aston Martin', 'db11': 'Aston Martin',
  'vantage': 'Aston Martin', 'valkyrie': 'Aston Martin',
  // Toyota
  'toyota': 'Toyota', 'supra': 'Toyota', 'ae86': 'Toyota', 'corolla': 'Toyota',
  '2000gt': 'Toyota', 'tacoma': 'Toyota', 'tundra': 'Toyota', 'prius': 'Toyota',
  'land cruiser': 'Toyota', 'fj cruiser': 'Toyota', 'camry': 'Toyota',
  // Nissan
  'nissan': 'Nissan', 'gt-r': 'Nissan', 'gtr': 'Nissan', 'skyline': 'Nissan',
  '370z': 'Nissan', '350z': 'Nissan', 'silvia': 'Nissan', 'z32': 'Nissan',
  'patrol': 'Nissan', 'frontier': 'Nissan',
  // Honda
  'honda': 'Honda', 'civic': 'Honda', 'nsx': 'Honda', 's2000': 'Honda',
  'accord': 'Honda', 'crv': 'Honda', 'odyssey': 'Honda',
  // Mazda
  'mazda': 'Mazda', 'rx-7': 'Mazda', 'rx7': 'Mazda', 'miata': 'Mazda',
  'mx-5': 'Mazda', '787b': 'Mazda',
  // Subaru
  'subaru': 'Subaru', 'wrx': 'Subaru', 'brz': 'Subaru', 'impreza': 'Subaru',
  'outback': 'Subaru', 'forester': 'Subaru',
  // Mitsubishi
  'mitsubishi': 'Mitsubishi', 'eclipse': 'Mitsubishi', 'lancer': 'Mitsubishi',
  'evolution': 'Mitsubishi', 'evo': 'Mitsubishi',
  // Volkswagen
  'volkswagen': 'Volkswagen', 'vw': 'Volkswagen', 'beetle': 'Volkswagen', 'golf': 'Volkswagen', 'gti': 'Volkswagen',
  'scirocco': 'Volkswagen', 'kool kombi': 'Volkswagen',
  'amarok': 'Volkswagen',
  // Land Rover / Jeep
  'land rover': 'Land Rover', 'defender': 'Land Rover', 'discovery': 'Land Rover',
  'range rover': 'Land Rover', 'jeep': 'Jeep', 'wrangler': 'Jeep',
  'cherokee': 'Jeep', 'gladiator': 'Jeep', 'scrambler': 'Jeep',
  // Others
  'tesla': 'Tesla', 'rivian': 'Rivian', 'mini': 'MINI', 'fiat': 'Fiat',
  'alfa romeo': 'Alfa Romeo', 'maserati': 'Maserati', 'lotus': 'Lotus',
  'shelby': 'Shelby', 'delorean': 'Delorean', 'rolls royce': 'Rolls Royce',
  'bentley': 'Bentley', 'jaguar': 'Jaguar', 'volvo': 'Volvo',
  'saab': 'Saab', 'peugeot': 'Peugeot', 'renault': 'Renault',
  'citroen': 'Citroen', 'bmw m': 'BMW',
  // School bus / Surfin
  'school bus': 'Hot Wheels Original',
  'surfin school bus': 'Hot Wheels Original',
  'surfin': 'Hot Wheels Original',
  // Datsun
  'datsun': 'Datsun',
  '240z': 'Datsun',
  '260z': 'Datsun',
  '280z': 'Datsun',
  '510': 'Datsun',
  'bluebird': 'Datsun',
  'fairlady': 'Datsun',
  // Volkswagen specific
  'volkswagen': 'Volkswagen',
  'vw bug': 'Volkswagen',
  'kool kombi': 'Volkswagen',
  'samba bus': 'Volkswagen',
  'scirocco': 'Volkswagen',
  'amarok': 'Volkswagen',
  // Hot Wheels originals
  'bone shaker': 'Hot Wheels Original', 'twin mill': 'Hot Wheels Original',
  'deora': 'Hot Wheels Original', 'rip rod': 'Hot Wheels Original',
  'rodger dodger': 'Hot Wheels Original', 'ratbomb': 'Hot Wheels Original',
  'bread box': 'Hot Wheels Original', 'rocket box': 'Hot Wheels Original',
  'fast fish': 'Hot Wheels Original', 'nitro doorslammer': 'Hot Wheels Original',
};

// Auto-detect manufacturer from car name
export function detectManufacturer(carName: string): string {
  if (!carName) return '';
  const lower = carName.toLowerCase();
  // Check longest match first
  const keys = Object.keys(NAME_TO_MFG).sort((a, b) => b.length - a.length);
  for (const key of keys) {
    if (lower.includes(key)) return NAME_TO_MFG[key];
  }
  return '';
}

// Hot Wheels cars list
export const HW_CARS = [
  'Ford Mustang GTD',
  'Ferrari 296 GTB',
  'Porsche 911 GT3 R 992',
  'Nightspeed',
  'Fiat Beast of Turin',
  'Purple Passion',
  'Dino 206 GT',
  'Ford F-150 Lightning SuperTruck',
  'BMW M3 Wagon',
  'Polester TRX',
  'Triumph TR6',
  '1983 Porsche 928S',
  'Drop Tops',
  'X-Raycers',
  'Exoticars',
  'HW Heavyweights',
  'HW Euro',
  'HW Drag Racers',
  'Layin Low',
  'Truckin Along',
  'Volvo P1800 Gasser',
  '87 Ford Sierra Cosworth',
  'Classic TV Series Batmobile',
  'Ford Escort RS2000',
  'Dimachinni Veloce',
  'HW KITT Concept',
  'Nissan Patrol Custom',
  '1970 Pontiac Firebird',
  '17 Pagani Huayra Roadster',
  'Corvette Grand Sport Roadster',
  '85 Honda City Turbo II',
  'Morgan Super 3',
  '68 Corvette Gas Monkey Garage',
  'Mazda Autozam',
  'Back to the Future Time Machine Hover Mode',
  '70 Plymouth Barracuda',
  'Fiat 500e',
  '2020 Ram 1500 Rebel',
  'Porsche 911 Carrera RS 2.7',
  '72 Stingray Convertible',
  'Honda Civic Si',
  'Nissan Skyline RS KDR30',
  '57 Jeep FC',
  '15 Mazda MX-5 Miata',
  'McLaren Solus GT',
  '87 Dodge D100',
  '55 Chevy Bel Air Gasser',
  '18 Camaro SS',
  'Custom 68 Camaro',
  '89 Mercedes-Benz 560 SEC AMG',
  '76 Greenwood Corvette',
  'Czinger 21C',
  'Volvo XC40 Recharge',
  'Tesla Model Y',
  'Audi RS e-tron GT',
  'Ford F-150 Lightning Custom',
  'GMC Hummer EV',
  'Corvette C6',
  'BMW 507',
  '47 Chevy Fleetline',
  '19 Ford Ranger Raptor',
  '07 Chevy Tahoe',
  'Mad Mike Drift Attack',
  'El Segundo Coupe',
  'Mod Speeder',
  'Lolux',
  '65 Ford Mustang Fastback',
  '67 Ford Mustang',
  '69 Ford Mustang',
  'Ford GT Heritage Edition',
  'Shelby Cobra 427',
  'COPO Camaro',
  'Corvette C8.R',
  '62 Corvette',
  '70 Chevelle SS',
  '68 El Camino',
  '71 El Camino',
  '64 Nova Gasser',
  '70 Dodge Challenger',
  '69 Dodge Charger',
  '70 Charger',
  '69 Charger Daytona',
  'Dodge Viper SRT',
  '71 Dodge Dart',
  'Plymouth Superbird',
  '67 Pontiac Firebird',
  '77 Trans Am',
  'Pontiac GTO',
  '71 AMC Javelin AMX',
  'AMC Gremlin',
  'Ferrari 812 Superfast',
  'Ferrari SF90 Stradale',
  'Lamborghini Huracan STO',
  'Lamborghini Diablo',
  'LB Super Silhouette Nissan Silvia S15',
  'Porsche 911 GT3 RS',
  'Porsche 935',
  'Porsche 962',
  'Mercedes-Benz 300 SL',
  'Audi RS 6 Avant',
  'Pagani Zonda Cinque',
  'Rimac Nevera',
  'Aston Martin Valkyrie',
  '82 Toyota Supra',
  '21 Toyota GR Supra',
  'Toyota AE86 Trueno',
  'Toyota AE86 Levin',
  'Toyota Celica TA22',
  'Toyota GR Yaris',
  'Toyota GR86',
  'Toyota MR2',
  'Nissan Skyline GT-R BNR32',
  'Nissan Silvia S15',
  'Nissan 240SX',
  'Nissan 180SX',
  'Nissan Fairlady Z',
  '90 Honda Civic EF',
  'Honda CR-X',
  'Honda Prelude',
  'Honda CB750 Cafe',
  'Honda S660',
  '93 Mazda RX-7',
  '95 Mazda RX-7',
  'Subaru Impreza WRC',
  'Subaru BRAT',
  'Mitsubishi 3000GT VR-4',
  'Mitsubishi Starion',
  'Volkswagen T2 Pickup',
  'Volkswagen Samba Bus',
  'Custom Otto',
  'Punk Rod',
  'Road Bandit',
  'Drift n Break',
  'Hot Wheels High',
  'Knight Draggin',
  'Group C Fantasy',
  'West Coast Flyer',
  'Batmobile',
  'Batmobile Dark Knight',
  'Batman Tumbler',
  'Back to the Future Time Machine',
  'Ghostbusters Ecto-1',
  'Barbie Corvette',
  '1956 Corvette Barbie The Movie',
  'TMNT Party Wagon',
  'Bone Shaker','Twin Mill','Deora II','Deora III','Rip Rod','Fast Fish',
  'Rodger Dodger','Nitro Doorslammer','Bread Box','Ratbomb','Rocket Box',
  'Power Pistons','Surfin School Bus','School Bus','Bad Mudder',
  'Ford Mustang','Ford Mustang GT','Ford Mustang Boss 302','Ford Mustang Mach 1',
  'Ford Mustang Mach-E','65 Mustang Fastback','67 Mustang','69 Mustang',
  '71 Mustang Mach 1',
  'Camaro','67 Camaro','69 Camaro','2018 Camaro SS','2021 Camaro SS',
  'Corvette','63 Corvette','65 Corvette','71 Corvette Stingray','80s Corvette',
  'C8 Corvette','Corvette Grand Sport','Corvette ZR1','Corvette C7Z06',
  'Dodge Challenger','Dodge Charger','Dodge Viper','Dodge Dart',
  'Plymouth Barracuda','Plymouth Road Runner','70 Plymouth Superbird',
  'Chevrolet Silverado','Chevy C10','67 Chevy C10','57 Chevy','55 Chevy',
  'Bel Air','El Camino','Monte Carlo SS','Nova','Impala','Chevelle SS',
  'Ford F-150','Ford F-100','Ford GT','Ford GT40','GT-40',
  'Ferrari 458 Italia','Ferrari 488 GTB','Ferrari F40','Ferrari F50',
  'Ferrari 599XX','Ferrari LaFerrari','Ferrari 308 GTS','Ferrari Testarossa',
  'Ferrari 250 GTO','Ferrari Enzo',
  'Lamborghini Countach','Lamborghini Huracan','Lamborghini Aventador',
  'Lamborghini Urus','Lamborghini Sesto Elemento','Lamborghini Gallardo',
  'Lamborghini Murcielago',
  'Porsche 911','Porsche 911 GT3','Porsche 918 Spyder','Porsche Cayenne',
  'Porsche 914','Porsche Cayman','Porsche 356A Outlaw','Porsche Carrera GT',
  'BMW M3','BMW M4','BMW 2002','BMW M5','BMW 1M','BMW i8',
  'Mercedes-Benz SLS AMG','Mercedes-Benz G-Class','Mercedes AMG GT',
  'Audi R8','Audi TT','Audi RS6','Audi Quattro',
  'McLaren P1','McLaren Senna','McLaren 720S','McLaren F1','McLaren 570S',
  'Bugatti Veyron','Bugatti Chiron','Bugatti Divo',
  'Koenigsegg Agera R','Koenigsegg Jesko','Pagani Huayra','Pagani Zonda',
  'Tesla Roadster','Tesla Cybertruck','Rivian R1T',
  'Ford Bronco','Ford Bronco R','Ford Maverick',
  'Jeep Scrambler','Jeep CJ-7','Jeep Wrangler',
  'Toyota Supra','Toyota AE86','Toyota 2000GT','Toyota Tacoma','Toyota Land Cruiser',
  'Nissan GT-R','Nissan Skyline','Nissan 370Z','Nissan Silvia','Nissan Z',
  'Honda Civic','Honda NSX','Honda S2000','Honda Civic Type R',
  'Mazda RX-7','Mazda MX-5 Miata','Mazda 787B','Mazda RX-3',
  'Subaru WRX STI','Subaru BRZ','Mitsubishi Eclipse','Mitsubishi Lancer Evolution',
  'Volkswagen Beetle','VW Bug','Kool Kombi','Volkswagen Golf GTI',
  'Volkswagen Scirocco','Volkswagen Amarok',
  'MINI Cooper','Fiat 500','Aston Martin DB5','Aston Martin Vantage',
  'Land Rover Defender','Land Rover Series III','Range Rover',
  'Shelby GT500','Shelby Cobra','Shelby GT350',
  'Rolls Royce Phantom','Bentley Continental',
  'Alfa Romeo Giulia','Maserati MC20',
  'Police Car','Ambulance','Fire Engine','Fire Truck',
  'Monster Truck','Baja Truck','Sand Blaster',
  'Datsun 240Z','Datsun 260Z','Datsun 280Z',
  'Datsun 510','Datsun 510 Bluebird',
  'Datsun Bluebird Wagon','Datsun 620 Pickup',
  'Datsun 1600 Roadster','Datsun B210','Datsun Fairlady',
  'Dragster','Top Fuel Dragster','Funny Car','Formula 1 Car','NASCAR Stock Car',
  'Dump Truck','Tow Truck','Semi Truck','Big Rig',
];

// Matchbox cars list
export const MB_CARS = [
  'Ford Transit','Ford Ranger','Ford Maverick','Ford Edge','Ford Bronco',
  'Chevy Suburban','Chevy Tahoe','Chevy Silverado','Chevy Blazer',
  'Dodge Challenger','Dodge Charger','Dodge Ram',
  'Toyota Land Cruiser','Toyota Hilux','Toyota Tacoma','Toyota Tundra',
  'Toyota Prius','Toyota Corolla',
  'Mercedes G-Wagon','Mercedes Sprinter','BMW X5','BMW X7','Audi Q7','Audi e-tron',
  'Land Rover Defender','Land Rover Discovery','Range Rover','Range Rover Sport',
  'Jeep Wrangler','Jeep Cherokee','Jeep Gladiator','Jeep Compass',
  'Police Car','Police Truck','Police Helicopter','Police Motorcycle',
  'Ambulance','Fire Engine','Fire Truck','Fire Ladder Truck','Fire Rescue',
  'School Bus','City Bus','Double Decker Bus','Transit Bus',
  'Garbage Truck','Dump Truck','Tow Truck','Semi Truck','Box Truck',
  'Construction Crane','Bulldozer','Excavator','Cement Mixer','Grader',
  'Airport Fire Truck','Airport Rescue','Helicopter','Coast Guard Boat',
  'Monster Truck','Off Road Truck','Dune Buggy','Sand Rail',
  'Subaru WRX','Honda Civic Type R','Mitsubishi Eclipse Cross',
  'Volkswagen Amarok','Volkswagen Transporter','Volkswagen ID.4',
  'Porsche 911','Porsche Cayenne','Ferrari','Lamborghini Huracan',
  'Nissan GT-R','Nissan Patrol',
  'Tesla Model S','Tesla Model 3','Tesla Cybertruck',
  'Corvette','Camaro','Mustang',
  'Superfast','Moving Parts','MBX Series',
];

// Search cars
export function searchCars(query: string, brand: 'hw' | 'mb'): string[] {
  if (!query || query.length < 2) return [];
  const q = query.toLowerCase();
  const list = brand === 'hw' ? HW_CARS : MB_CARS;
  return list.filter(name => name.toLowerCase().includes(q)).slice(0, 12);
}

// Search manufacturers
export function searchManufacturers(query: string): string[] {
  if (!query) return MANUFACTURERS.slice(0, 20);
  const q = query.toLowerCase();
  return MANUFACTURERS.filter(m => m.toLowerCase().includes(q)).slice(0, 15);
}
